name: Hello world
on: workflow_dispatch
jobs: 
  Hello-world:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello
        run: echo "Hello dad"
      - name: goodbye
        run: echo "good bye"
    
